exclude: "node_modules"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: detect-private-key
      - id: detect-aws-credentials
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.54.0" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint-config-alloy@latest
          - "@typescript-eslint/eslint-plugin@latest"
          - eslint-plugin-react@latest
          - "@typescript-eslint/parser@latest"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types: [json, yaml, markdown, javascript, css, html, jsx, ts, tsx]
